services:
  - type: web
    name: hirecircle-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn HireCircle.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
